{% set version = "0.2.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rvg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rvg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rvg/rvg_{{ version }}.tar.gz
  sha256: 0544d3fbfcde6be5921a72505a82614654ee2d2b774cc4ab60f1c582ef95f089

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-gdtools >=0.2.1
    - r-officer >=0.3.6
    - r-rlang
    - r-xml2 >=1.0.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.12.12
    - r-gdtools >=0.2.1
    - r-officer >=0.3.6
    - r-rlang
    - r-xml2 >=1.0.0

test:
  commands:
    - $R -e "library('rvg')"           # [not win]
    - "\"%R%\" -e \"library('rvg')\""  # [win]

about:
  home: https://github.com/davidgohel/rvg
  license: GPL-3
  summary: Vector Graphics devices for Microsoft  PowerPoint and Excel. Functions extending package
    'officer' are provided to  embed 'DrawingML' graphics into 'Microsoft PowerPoint'
    presentations and  'Microsoft Excel' workbooks.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rvg
# Type: Package
# Title: R Graphics Devices for Vector Graphics Output
# Version: 0.2.1
# Authors@R: c( person("David", "Gohel", role = c("aut", "cre"), email = "david.gohel@ardata.fr"), person("Bob", "Rudis", role = c("ctb"), comment = "the javascript code used by function set_attr"), person("Francois", "Brunetti", role = c("ctb"), email = "francois.brunetti@lysis-consultants.fr", comment = "clipping algorithms") )
# Description: Vector Graphics devices for Microsoft  PowerPoint and Excel. Functions extending package 'officer' are provided to  embed 'DrawingML' graphics into 'Microsoft PowerPoint' presentations and  'Microsoft Excel' workbooks.
# License: GPL-3
# Encoding: UTF-8
# Depends: R (>= 3.0)
# Imports: grDevices, Rcpp (>= 0.12.12), officer (>= 0.3.5), gdtools (>= 0.1.6), xml2 (>= 1.0.0), rlang
# LinkingTo: Rcpp, gdtools
# Suggests: htmltools, testthat, covr, grid
# URL: https://github.com/davidgohel/rvg
# BugReports: https://github.com/davidgohel/rvg/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-06-24 22:50:51 UTC; davidgohel
# Author: David Gohel [aut, cre], Bob Rudis [ctb] (the javascript code used by function set_attr), Francois Brunetti [ctb] (clipping algorithms)
# Maintainer: David Gohel <david.gohel@ardata.fr>
# Repository: CRAN
# Date/Publication: 2019-06-25 09:30:03 UTC
