{% set version = "0.3.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rvg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rvg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rvg/rvg_{{ version }}.tar.gz
  sha256: 80917103dbdba98d46c052106d8ee0e97c093feb07fea25bda2a34d3e5c601f0

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-gdtools >=0.3.3
    - r-officer >=0.6.2
    - r-rlang
    - r-xml2 >=1.0.0
    - libpng
    - zlib
  run:
    - r-base
    - r-rcpp >=0.12.12
    - r-gdtools >=0.3.3
    - r-officer >=0.6.2
    - r-rlang
    - r-xml2 >=1.0.0

test:
  commands:
    - $R -e "library('rvg')"           # [not win]
    - "\"%R%\" -e \"library('rvg')\""  # [win]

about:
  home: https://github.com/davidgohel/rvg
  license: GPL-3.0-only
  summary: Vector Graphics devices for Microsoft PowerPoint and Excel. Functions extending package 'officer' are provided to  embed 'DrawingML' graphics into 'Microsoft PowerPoint' presentations and  'Microsoft Excel' workbooks.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
