travis:
  secure:
    BINSTAR_TOKEN: ZLT4CJGj8lr9ebB1youuTGqgEnxaSKZ2+ZRt2urHAGUsOLuy5ZkGT0QMNZjnicufJcWsSE4uJE2pHGR8wy1zSWn9SsRR8nyBZ9U+vW0Mx93jCtws9dup4uzC2HpXF+CGIv4GF1g5oDeevadr8FXZOqGngkITc0NDZ2BlmcAujpPXdWCbWYNBQpvvNCl+zBYLEl3SgSjC/VTYrNjh9qgBuaXSvDMQ+gey/MSmWyIS+pBVY6JCgXXlqUqN0RFf3c0KntAFAs/FYDTXoQ9Pj3XcV2P50OzYejeOzaDDcxtS0dw+9ojMPaSxahhDviSdg+F4HbHjaapqTzuR471/shGLaZZeROLkAnW4n96YNCRdqF/l6VrTlICiIMYh33abIUv8YPfI7p+LQppe3AIcm7HTFqmtWsEQDUFOhLLDjf10cZeXlQIpd/23CjOfHQN0mRpaRXdPyYU5Kg88MCG5YkBoFrFNe44YYYCyYASJYpTjqvO48+x6ZKD40R3Tj4RvVF5oCPv6YD41CVkeitc9OL5Uvj0tUbA6mFAyrmGDBxUAuRKcH8lMfASE4u/EPCckhrnz8PuaD5dUw1RURFM8O7tSpxsUEWEDucFkH3Qo6UbSPUmrXp/sMH+k3CnkxVjU+MYtnbRFaHJCVePdLzyiqKVhhFUkIeyC+tLgNTRFPDwhL1E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
